### ISSUE TITLE
multiple words search in spacemacs

### ISSUE THREAD

**Issue by chu-** [dfeich/helm-deft#3]
Hi dfeich,
I am using Spacemacs with helm-deft and really like this extension, but one issue that when I search more than one word, the Spacemacs give no search results and doesn't response in several seconds.
Thanks.

**Comment by dfeich** [comment]
Dear Chu
The search is implemented by a subprocess running a shell command (start-process-shell-command). The shell command that is built consists of a recursive chain of `grep`commands like:

> grep  -EHine 'expr3' $(grep  -Elie 'expr2' $(grep  -Elie 'expr1' file1 file2))

So, the greps evaluated at the beginning deliver a list of matching files and hand it over to the next grep, until the outermost grep then really pulls out the lines from the remaining files where the last expr  matched. This should work on all unix-like shells. Maybe you should first test whether this kind of command line works.

You can see what the line looks like by running this in the scratch buffer
```
(helm-deft-build-cmd  "expr1 expr2 expr3"  '("file1" "file2"))
```

Once you can confirm that such a search command works in your shell, one can go on with debugging the upper layer.

**Comment by chu-** [comment]
Dear Derek,

Thanks for reply.

In: (helm-deft-build-cmd  "expr1 expr2 expr3"  '("file1" "file2"))

Out:  "grep  -EHine 'expr3' $(grep  -Elie 'expr2' $(grep  -Elie 'expr1'
file1 file2))"
I tested "grep  -EHine 'expr3' $(grep  -Elie 'expr2' $(grep  -Elie 'expr1'
file1 file2))" on Bash, no problem.
I use Fish shell as default shell (ansi-ferm in Emacs), do you think that's
the point?

**Comment by dfeich** [comment]
Dear Chu
Sorry for the late reply. Yes, your problem derives from fish shell. In bash the syntax `$(command)` is used to insert at its place the results of the executed command. Like in most shells one can also use backticks in bash. I prefer the `$()` notation.

Now in fish shell seemingly the syntax is just `(command)`. I looked it up in the documentation at 
https://fishshell.com/docs/current/tutorial.html#tut_command_substitutions. I am not using fish shell myself. So, you could change this part of my code, or you could try to execute everything in bash.

As I said, this is not a code fit for distribution and the dependence on a particular shell (bash) is certainly bad, but I currently have no time to make this generic.

**Comment by chu-** [comment]
Dear Derek,
Yes you are right. Fish shell use (command) instead of $(command).
Thanks for your suggestions.
