### ISSUE TITLE
pb with helm-log

### ISSUE THREAD

**Issue by yherve** [dfeich/helm-deft#6]
Hi, I've just updated my list of emacs packages and there is now an error with helm-deft:

error in process sentinel: cond: Wrong number of arguments

I took a look, it seems that helm-log now takes an extra "FROM" argument

So if you search/replace helm-log with helm-log "helm-deft", it works fine.

I want to thank you again for helm-deft. It's awesome I use it all the time

**Comment by dfeich** [comment]
Thanks a lot @yherve and welcome. Will update once I have enough time. Had no time to update my Emacs in the last 2 months, so need to wait for a moment where my workload allows for some instability.

**Comment by dfeich** [comment]
Sorry for taking so long... must have been the longest time I did not update anything in my config. Thanks again.
